README.md, doc/sorter-adapters.md, doc/sorter-traits.md, doc/sorters.md, include/cpp-sort/sorter_traits.h, include/cpp-sort/sorters/counting_sorter.h, include/cpp-sort/sorters/default_sorter.h, include/cpp-sort/sorters/hybrid_sorter.h, include/cpp-sort/sorters/insertion_sorter.h, include/cpp-sort/sorters/merge_sorter.h, include/cpp-sort/sorters/pdq_sorter.h, include/cpp-sort/sorters/small_array_sorter.h, include/cpp-sort/sorters/std_sorter.h, include/cpp-sort/sorters/tim_sorter.h
Add `sorter_traits` which give information about a sorter's stability and the kind of iterators it works with. Use the latter property to implement `hybrid_sorter`, a sorter which can combine several sorters into one provided they work with different kinds of iterators.
=> Hybrid sorter

benchmarks/bars.py, benchmarks/bench.cpp, doc/sorters.md, include/cpp-sort/adapters/counting_adapter.h, include/cpp-sort/adapters/hybrid_adapter.h, include/cpp-sort/adapters/self_sort_adapter.h, include/cpp-sort/adapters/small_array_adapter.h, include/cpp-sort/detail/sorter_base.h, include/cpp-sort/sorter_base.h, include/cpp-sort/sorters/heap_sorter.h, include/cpp-sort/sorters/inplace_merge_sorter.h, include/cpp-sort/sorters/insertion_sorter.h, include/cpp-sort/sorters/merge_sorter.h, include/cpp-sort/sorters/pdq_sorter.h, include/cpp-sort/sorters/quick_sorter.h, include/cpp-sort/sorters/std_sorter.h, include/cpp-sort/sorters/tim_sorter.h, include/cpp-sort/sorters/verge_sorter.h
Add a `cppsort::sorter_base` class tempate and use it almost everywhere to add to the sorters and sorter adapters the possibiity to be converted to several kinds of function pointers. It allows for unary and binary function pointers conversions through the use of captureless lambdas (with or without `Compare`). Update documentation accordingly.
=> Function pointers conversions for sorters

README.md, doc/sort.md, doc/sorter-adapters.md, doc/sorter-base.md, doc/sorter-traits.md, doc/sorters.md, include/cpp-sort/adapters/counting_adapter.h, include/cpp-sort/adapters/hybrid_adapter.h, include/cpp-sort/adapters/self_sort_adapter.h, include/cpp-sort/adapters/small_array_adapter.h, include/cpp-sort/sort.h, include/cpp-sort/sorter_base.h, include/cpp-sort/sorter_traits.h, include/cpp-sort/sorters/heap_sorter.h, include/cpp-sort/sorters/inplace_merge_sorter.h, include/cpp-sort/sorters/insertion_sorter.h, include/cpp-sort/sorters/merge_sorter.h, include/cpp-sort/sorters/pdq_sorter.h, include/cpp-sort/sorters/quick_sorter.h, include/cpp-sort/sorters/std_sorter.h, include/cpp-sort/sorters/tim_sorter.h, include/cpp-sort/sorters/verge_sorter.h
This update adds an iterator interface to every sorter and sorter adapter in the library. It also mandates that types satisfying the `Sorter` and `ComparisonSorter` concepts shall be callable with a pair of iterators so that they can sort more than full collections.
The update also introduces `sorter_base`, a CRTP class design to ease the writing of simpe sorters. Most of the sorters available in the library make use of this class to reduce boilerplate.
=> Iterator interface for sorters

README.md, benchmarks/bars.py, benchmarks/bench.cpp, doc/sorters.md, include/cpp-sort/detail/spreadsort/detail/common.h, include/cpp-sort/detail/spreadsort/detail/constants.h, include/cpp-sort/detail/spreadsort/detail/float_sort.h, include/cpp-sort/detail/spreadsort/detail/integer_sort.h, include/cpp-sort/detail/spreadsort/detail/string_sort.h, include/cpp-sort/detail/spreadsort/float_sort.h, include/cpp-sort/detail/spreadsort/integer_sort.h, include/cpp-sort/detail/spreadsort/string_sort.h, include/cpp-sort/sorters/spread_sorter.h, include/cpp-sort/sorters/spread_sorter/float_spread_sorter.h, include/cpp-sort/sorters/spread_sorter/integer_spread_sorter.h, include/cpp-sort/sorters/spread_sorter/string_spread_sorter.h, testsuite/CMakeLists.txt, testsuite/sorters/spread_sorter.cpp
This patch adds the non-comparison sorters `integer_spread_sorter`, `float_sorter`, `string_sorter` as well the aggregated `spread_sorter` to the library. The code comes directly from Boost.Sort and has been alterated so that it can integrate seamlessly into cpp-sort without having to rely on other Boost modules anymore (we only lose the static warnings, it's not *that* bad).
Basically, these new sorters are an interesting way to test the non-comparison sorters support as well as the recently empowered `hybrid_adapter`. The testsuite and the documentation have been completed to reflect the additions.
=> Add Boost.Sort's spreadsort to the library

doc/writing-sorter.md, include/cpp-sort/sorter_base.h, testsuite/CMakeLists.txt, testsuite/adapters/hybrid_adapter_partial_compare.cpp, testsuite/adapters/hybrid_adapter_sfinae.cpp, testsuite/sorter_base_std_less.cpp, testsuite/sorters/default_sorter.cpp, testsuite/sorters/default_sorter_fptr.cpp, testsuite/sorters/spread_sorter.cpp
This branch adds the notion of partial comparison sorters to the library and updates the testsuite and the documentation accordingly. Until there, a sorter could either be a full comparison sorter and take any comparison function to sort its collection, or be a strict non-comparison sorter, taking no comparison function at all, and always sort the collection in ascending order.
This update allows to overload a sorter's `operator()` for specific comparison functions and defines a set of rules to make sure that everything goes smoothly when they are enforced (even though the library itself does not enforce them). `sorter_base` has also been updated so that any sorter can be called with `std::less` or `std::less<T>` to sort a collection in ascending order, regardless of whether the original …
=> Allow to use comparison function objects a tags

doc/sorters.md, include/cpp-sort/detail/bubble_sort.h, include/cpp-sort/detail/insertion_sort.h, include/cpp-sort/detail/iter_sort3.h, include/cpp-sort/detail/pdqsort.h, include/cpp-sort/detail/quicksort.h, include/cpp-sort/sorters/default_sorter.h, include/cpp-sort/sorters/insertion_sorter.h, include/cpp-sort/sorters/quick_sorter.h
This branch makes `quick_sorter` work with forward iterators instead of simply bidirectional iterators. It also updates the quicksort implementation to use a deterministic median-of-3 pivot to reduce the chances of quadratic behaviour. The following changes have also been made because they are or were needed at some point:
* `insertion_sorter` works with forward iterators too (even though it isn't really efficient).
* A special bubble sort implementation has been added for fallbacks.
* `sort3` has been factored out of pdqsort.h and renamed `iter_sort3`.
* Quicksort and insertion sort both use tag dispatch to switch to use a more efficient implementation depending on the iterator category of the collection to sort.
* `default_sorter` rebinds `quick_sorter`'s iterator category to …
=> Make quick_sorter work with forward iterators

include/cpp-sort/sorter_facade.h, testsuite/sorter_facade_std_less.cpp, testsuite/sorters/spread_sorter_defaults.cpp
Remove default support for `std::less<T>` from `sorter_facade` and the associated tests. The library was never meant to be legacy-friendly anyway and it introduced some inconsistencies as well as making tests fail with Clang and increasing the maintainance cost. We call live without them and use `std::less<>` everywhere instead.
=> Nuke std::less<T> overloads in sorter_facade.

.travis.yml
Add full leak check for the testsuite with Valgrind in .travis.yml. Apparently, there isn't a single memory error as of right now, so... nothing more to do.
=> Tentative Valgrind support in Travis.

include/cpp-sort/detail/block_sort.h, include/cpp-sort/sorters.h, include/cpp-sort/sorters/block_sorter.h
This pull request adds a `block_sorter` wrapping BonzaiThePenguin's [WikiSort](https://github.com/BonzaiThePenguin/WikiSort), which is an implementation of the [block sort](https://en.wikipedia.org/wiki/Block_sort) algorithm proposed by Pok-Son Kim and Arne Kutzner. I have updated the original implementation to handle projection parameters.
=> Add a block_sorter to the library (issue #23).

include/cpp-sort/detail/exact_sort.h, include/cpp-sort/sorters.h, include/cpp-sort/sorters/exact_sorter.h
This pull request adds an `exact_sorter` to the library, which is an enhanced version of Ahmet Akkök's [Exact-Sort](http://www.geocities.ws/p356spt/). The algorithm has been reimplemented in C++ and changed a bit to actually perform a minimal number of move operations. It has also been enhanced to support user-provided comparison and projection functions.
=> Add an exact_sorter to the library (issue #23).

include/cpp-sort/detail/grail_sort.h, include/cpp-sort/detail/merge_move.h, include/cpp-sort/sorters.h, include/cpp-sort/sorters/grail_sorter.h
This pull request adds the buffered sorter `grail_sorter` to the library, wrapping Mrrl's [GrailSort](https://github.com/Mrrl/GrailSort), which is an implementation of a stable sorting algorithm described by B-C. Huang and M. A. Langston. I have ported the original implementation to C++, making it work with any random-access iterator and handle comparison and projection parameters.
A sorting algorithm close to Mrrl's [SqrtSort](https://github.com/Mrrl/SqrtSort) can be obtained with `grail_sorter<dynamic_buffer<sqrt>>`.
=> Add a grail_sorter to the library (issue #23).

examples/bubble_sorter.cpp, include/cpp-sort/adapters/counting_adapter.h, include/cpp-sort/adapters/hybrid_adapter.h, include/cpp-sort/adapters/indirect_adapter.h, include/cpp-sort/adapters/self_sort_adapter.h, include/cpp-sort/adapters/small_array_adapter.h, include/cpp-sort/detail/checkers.h, include/cpp-sort/detail/raw_checkers.h, include/cpp-sort/sorter_traits.h, include/cpp-sort/sorters/block_sorter.h, include/cpp-sort/sorters/grail_sorter.h, include/cpp-sort/sorters/heap_sorter.h, include/cpp-sort/sorters/insertion_sorter.h, include/cpp-sort/sorters/merge_sorter.h, include/cpp-sort/sorters/pdq_sorter.h, include/cpp-sort/sorters/quick_sorter.h, include/cpp-sort/sorters/selection_sorter.h, include/cpp-sort/sorters/smooth_sorter.h, include/cpp-sort/sorters/spread_sorter/float_spread_sorter.h, include/cpp-sort/sorters/spread_sorter/integer_spread_sorter.h, include/cpp-sort/sorters/spread_sorter/string_spread_sorter.h, include/cpp-sort/sorters/std_sorter.h, include/cpp-sort/sorters/std_stable_sorter.h, include/cpp-sort/sorters/tim_sorter.h, include/cpp-sort/sorters/verge_sorter.h, testsuite/adapters/hybrid_adapter_partial_compare.cpp, testsuite/adapters/hybrid_adapter_sfinae.cpp, testsuite/adapters/small_array_adapter.cpp, testsuite/rebind_iterator_category.cpp
This branch gives to the generic version of `sorter_traits` the ability to find `is_stable` and `iterator_category` in the sorter it is passed, and uses this new ability to embed this information directly into the sorters and adapters when it is convenient instead of specializing `sorter_traits` (some sepcializations remain, still for convenience). Moreover, it goes to great lengths to make sure that the traits are as decoupled as possible. Ideally, when a trait is needed but another trait doesn't exist in a sorter, it should still compile more often than before.
=> Embed traits into sorters and adapters. Fixes #10.

include/cpp-sort/adapters/small_array_adapter.h, include/cpp-sort/fixed/low_comparisons_sorter.h, include/cpp-sort/fixed/low_moves_sorter.h, include/cpp-sort/fixed/sorting_network_sorter.h, include/cpp-sort/sorter_traits.h, testsuite/adapters/small_array_adapter.cpp
This branch adds a new class template `fixed_sorter_traits` which provides information about a fixed-size sorter, and most notably contains the type `domain` which tells which specializations of a fixed-size sorter trait are actually usable. `small_array_adapter` is enhanced to take this information into account and automagically know for which sizes of arrays it is supposed to use the fixed-size sorter even when we don't explicitly feed the information to it. It will use `domain` if possible and consider that every specialization is valid if this type does not exist.
=> Fixed sorter traits. Fixes #35.

include/cpp-sort/detail/static_const.h, include/cpp-sort/probes.h, include/cpp-sort/probes/dis.h, include/cpp-sort/probes/exc.h, include/cpp-sort/probes/ham.h, include/cpp-sort/probes/inv.h, include/cpp-sort/probes/max.h, include/cpp-sort/probes/osc.h, include/cpp-sort/probes/rem.h, include/cpp-sort/probes/runs.h, include/cpp-sort/utility/as_function.h, testsuite/CMakeLists.txt, testsuite/probes/dis.cpp, testsuite/probes/exc.cpp, testsuite/probes/ham.cpp, testsuite/probes/inv.cpp, testsuite/probes/max.cpp, testsuite/probes/osc.cpp, testsuite/probes/rem.cpp, testsuite/probes/runs.cpp
Add 8 standard measures of presortedness to the library in the `probe` subnamespace, complete with tests and documentation. More such measures could be added later but it's enough for now. These measures use `sorter_facade` behind the scenes to provide a full support for custom comparison and projection functions, with automatic additional overloads for `std::less<>` and `utility::identity` and ranges, and everything we want them to work with...
=> Add measures of presortedness. Fixes #48.

include/cpp-sort/detail/poplar_sort.h, include/cpp-sort/sorters.h, include/cpp-sort/sorters/poplar_sorter.h
The new `poplar_sorter` implements a *poplar sort* which is a heapsort derivative described by Coenraad Bron and Wim H. Hesselink in *Smoothsort revisited*. While heapsort uses a balanced binary heap and smoothsort uses a Leonardo heap, poplar sort uses a forest of perfect binary heaps whose root is stored on the right to make sure that the bigger elements in the collection are closer to their sorted position and thus to increase locality.
=> Add a poplar_sorter to the library.

examples/bubble_sorter.cpp, include/cpp-sort/detail/projection_compare.h, include/cpp-sort/sorter_facade.h, include/cpp-sort/sorters/std_sorter.h, include/cpp-sort/sorters/std_stable_sorter.h, testsuite/sorters/std_sorter.cpp
This branch enhances `sorter_facade` to handle projections even when the underlying *sorter implementation* does not handle them. The new overloads take the projection and bakes them into the passed comparison or in `std::less<>` if no comparison was passed, then passes that new enhanced comparison object to the *sorter implementation*. It allows to give free projections support to sorting algorithms that don't explicitly provide it, and notably to use projections with `std_sorter` and `std_stable_sorter`, even thought these algorithms don't handle them by default.
=> Automagic projections. Fixes #36.

include/cpp-sort/adapters/schwartz_adapter.h, include/cpp-sort/detail/associate_iterator.h, include/cpp-sort/detail/iterator_traits.h, include/cpp-sort/detail/spreadsort/detail/float_sort.h, include/cpp-sort/detail/spreadsort/detail/integer_sort.h, include/cpp-sort/detail/spreadsort/detail/string_sort.h, include/cpp-sort/detail/spreadsort/float_sort.h, include/cpp-sort/detail/spreadsort/integer_sort.h, include/cpp-sort/detail/spreadsort/string_sort.h, include/cpp-sort/sorters/spread_sorter/float_spread_sorter.h, include/cpp-sort/sorters/spread_sorter/integer_spread_sorter.h, include/cpp-sort/sorters/spread_sorter/string_spread_sorter.h, testsuite/CMakeLists.txt, testsuite/adapters/schwartz_adapter_every_sorter.cpp, testsuite/sorters/spread_sorter_projection.cpp
This branch acknowledges the fact that non-comparison sorters may still be able to handle projections too as long as the information about the items of the collection to sort is not discarded by the algorithm and the original sorter can handle the resulting type of the projection.
Acknowledging that fact is fun and all, but the branch also brings projection support for every flavour of `spread_sorter`, and also enchances `schwartz_adapter` so that it properly handles projection-only sorters. There is also a huge removal of unused functions in the source code of `spread_sorter`.
=> Handle projection-only type-specific sorters. Fixes #68.

examples/bubble_sorter.cpp, include/cpp-sort/adapters/counting_adapter.h, include/cpp-sort/adapters/hybrid_adapter.h, include/cpp-sort/adapters/self_sort_adapter.h, include/cpp-sort/detail/begin_end.h, include/cpp-sort/sort.h, include/cpp-sort/sorter_facade.h, include/cpp-sort/sorters/merge_sorter.h, include/cpp-sort/sorters/quick_sorter.h, include/cpp-sort/stable_sort.h, include/cpp-sort/utility/begin_end.h, include/cpp-sort/utility/size.h, testsuite/CMakeLists.txt, testsuite/adapters/counting_adapter.cpp, testsuite/adapters/indirect_adapter.cpp, testsuite/every_sorter_span.cpp, testsuite/span.h
This commit enhances sorters so that they can also sort temporary ranges. While this is useless at best and error-prone at worst for standard containers, it is required to handle temporary span-like classes such as `gsl::span` that are more and more common in the C++ realm, and that could even be standardized in a few years.
This also introduces `utility::begin` and `utility::end` (directly taken from Eric Niebler's Range v3) to bypass the fact that `std::begin` and `std::end` can't return mutable iterators when given rvalues.
=> Support for temporary span-like classes. Fixes #70.

include/cpp-sort/adapters/container_aware_adapter.h, include/cpp-sort/sort.h, include/cpp-sort/sorter_facade.h, include/cpp-sort/stable_sort.h, include/cpp-sort/utility/functional.h, testsuite/CMakeLists.txt, testsuite/sorter_facade_iterable.cpp, testsuite/utility/as_projection.cpp, testsuite/utility/as_projection_iterable.cpp
This branch implements the utility functions `as_projection` and `as_comparison` which help disambiguate functions that satisfy both concepts. It also alters `sort`, `stable_sort`, `sorter_facade` and `container_aware_adapter` to ensure that a mixed comparison/projection function is always implicitly considered to be a comparison function a the call would otherwise be ambiguous.
=> as_comparison and as_projection (fixes #79)

.travis.yml, testsuite/CMakeLists.txt, testsuite/adapters/container_aware_adapter_forward_list.cpp, testsuite/adapters/container_aware_adapter_list.cpp, testsuite/adapters/counting_adapter.cpp, testsuite/adapters/indirect_adapter.cpp, testsuite/adapters/indirect_adapter_every_sorter.cpp, testsuite/adapters/self_sort_adapter_no_compare.cpp, testsuite/distributions.h, testsuite/distributions/all_equal.cpp, testsuite/distributions/alternating.cpp, testsuite/distributions/alternating_16_values.cpp, testsuite/distributions/ascending.cpp, testsuite/distributions/ascending_sawtooth.cpp, testsuite/distributions/descending.cpp, testsuite/distributions/descending_sawtooth.cpp, testsuite/distributions/pipe_organ.cpp, testsuite/distributions/push_front.cpp, testsuite/distributions/push_middle.cpp, testsuite/distributions/shuffled.cpp, testsuite/distributions/shuffled_16_values.cpp, testsuite/every_instantiated_sorter.cpp, testsuite/every_sorter.cpp, testsuite/every_sorter_span.cpp, testsuite/probes/relations.cpp, testsuite/sorters/counting_sorter.cpp, testsuite/sorters/default_sorter.cpp, testsuite/sorters/default_sorter_fptr.cpp, testsuite/sorters/default_sorter_projection.cpp, testsuite/sorters/merge_sorter.cpp
Test sorters with specific data distributions, currently the ones used in the benchmarks, even though more specific patterns will probably be needed in the future (I'm looking at you, vergesort).
O(n²) sorts are left out of the tests (except quicksort) because the collections with specific distributions have 10000 elements, so these quadratic sorts would be way too slow. `counting_sort` doesn't appear in these tests either because it obviously doesn't care about patterns.
=> Add specific data distributions to tests (fixes #73)

include/cpp-sort/comparators/partial_greater.h, include/cpp-sort/comparators/partial_less.h, include/cpp-sort/comparators/total_greater.h, include/cpp-sort/comparators/total_less.h, include/cpp-sort/comparators/weak_greater.h, include/cpp-sort/comparators/weak_less.h, include/cpp-sort/detail/pdqsort.h, include/cpp-sort/utility/branchless_traits.h, include/cpp-sort/utility/functional.h, testsuite/CMakeLists.txt, testsuite/utility/branchless_traits.cpp
Add user-specializable traits to detect branchless comparison and projection functions. Update `pdq_sorter` to take these traits into account to pick the appropriate partitioning functions to use. This reflects the latest design changes in orlp/pdqsort while allowing users to provide additional information.
=> Add branchless traits to the library (fixes #101)

.travis.yml, testsuite/README.md, testsuite/adapters/counting_adapter.cpp, testsuite/adapters/mixed_adapters.cpp, testsuite/adapters/schwartz_adapter_every_sorter.cpp, testsuite/adapters/schwartz_adapter_fixed_sorters.cpp, testsuite/adapters/stable_adapter_every_sorter.cpp, testsuite/distributions.h, testsuite/every_sorter_move_only.cpp, testsuite/every_sorter_no_post_iterator.cpp, testsuite/sorters/default_sorter_projection.cpp, testsuite/sorters/merge_insertion_sorter_projection.cpp, testsuite/sorters/merge_sorter_projection.cpp, testsuite/sorters/ska_sorter.cpp, testsuite/sorters/ska_sorter_projection.cpp, testsuite/sorters/spread_sorter.cpp, testsuite/sorters/spread_sorter_defaults.cpp, testsuite/sorters/spread_sorter_projection.cpp, testsuite/sorters/std_sorter.cpp, testsuite/utility/as_projection.cpp, testsuite/utility/as_projection_iterable.cpp
Unfortunately, it only solves the problem of Catch failing tests, and does not help when Valgrind or a sanitizer fails. I'll leave it as is for now, but may add an unconditional dump of the seed, even when nothing is failing, just to make sure that it's logged when Valgrind or a sanitizer fails.
[ci skip]
=> Globally seed the testsuite PRNGs from the command line (fixes #108)

.gitignore, .travis.yml, external/catch/CMakeLists.txt, include/cpp-sort/utility/buffer.h, testsuite/CMakeLists.txt
Several changes to the Travis builds:
* Manually hand-roll the build matrix to handle specific cases
* Builds everything in a `build` subdirectory
* Builds on OSX with Xcode 8, with and without Valgrind
* Build with address sanitizer on Linux clang
* Proper build dependency in CMakeLists.txt
* Fix a bug to make clang builds work with libc++
=> Build overhaul, fixes #65, fixes #90

.travis.yml, CMakeLists.txt, external/catch/CMakeLists.txt, testsuite/CMakeLists.txt
Apply the following modifications to improve speed of CI:
* Enable apt cache and ccache
* Build with two jobs
* Compile with `CATCH_CONFIG_FAST_COMPILE`
* Link with gold linker
Apply the following other modifications:
* Explicitly build with Catch 1.x
* Reenable asan with GCC on Linux
=> Speed up CI

.travis.yml, conanfile.py, test_package/CMakeLists.txt, test_package/conanfile.py
Hi!
I just updated few points:
- Added compiler validation for MSVC. If Visual Studio is present, Conan will raise an exception.
- Copied license file to package folder.
- C++14 as required to build test_package
- Added Conan job on Travis. This job only will be executed on master branch. Also, the same job will upload the package to bintray after to create the package. It's necessary to fill the env  var `CONAN_PASSWORD` on your Travis settings. The password is your Bintray API Key.
Regards!
=> Support Conan package (#121)
